language: haskell
ghc:
  - 7.4
  - 7.6
  - 7.8
os:
  - linux
notifications:
  email: false
install:
  - cabal sandbox init
  - cabal install --only-dependencies
script:
  - cabal configure --ghc-option=-Werror
  - cabal build
sudo: false
